### ISSUE TITLE
The package do not build.

### ISSUE THREAD

**Issue by doubleailes** [pypoulp/oiio-python#1]
Hello,

I clone the repository and run at the root of the folder:
`pip install .` without any success.

It return `ImportError: No module named site`

**Comment by pypoulp** [comment]
❤️

**Comment by pypoulp** [comment]
Hi @doubleailes,

Jokes aside, it should be better now!

While `pip install .` should work, it builds everything locally using Conan, which might be more complex. It's easier to use the pre-built wheels instead:

`python -m pip install oiio-python`

Closing this one 😉
